version: "3.3"

services:
  flask:
    build:
      context: app/
      dockerfile: app.Dockerfile
    command: python main.py
    working_dir: /app
    volumes:
      - ./app/:/app/
    links:
      - database
    ports:
      - 5000:5000

  database:
    image: postgres:11.5-alpine
    volumes:
      - "db:/var/lib/postgresql/data"
      - ./:/app
    working_dir: /app
    expose:
      - 5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U 'postgres' -d postgres"]
      timeout: 10s
      interval: 20s
      retries: 3

volumes:
  db:
